project:
  type: website
  output-dir: docs

format:
  html:
    theme: cosmo
    toc: true
    math: mathjax
    number-sections: true

website:
  title: "Math 300 - Discrete Mathematics"
  sidebar:
    contents:
    - text: "Home"
      file: index.qmd
    - text: "Syllabus"
      file: syllabus/syllabus.qmd
    - section: "Homework"
      contents:
        - homework/homeworkwk2.qmd
        - homework/homeworkwk3.qmd
        - homework/homeworkwk4.qmd
        - homework/homeworkwk5.qmd
        - homework/homeworkwk7.qmd
        - homework/homeworkwk8.qmd
        - homework/homeworkwk9.qmd
        - homework/homeworkwk10.qmd
        - homework/homeworkwk11.qmd
        - homework/homeworkwk13.qmd
        - homework/homeworkwk14.qmd
        - homework/homeworkwk15.qmd
    - section: "Class Material"
      contents:
       - file: classes/01/worksheet.qmd
       - file: classes/01/slides.qmd
       - file: classes/02/worksheet1.qmd
       - file: classes/02/worksheet2.qmd
       - file: classes/02/slides.qmd
       - file: classes/03/worksheet.qmd
       - file: classes/03/slides.qmd
       - file: classes/04/worksheet s.qmd
       - file: classes/04/slides.qmd
       - file: classes/05/worksheet.qmd
       - file: classes/05/slides.qmd
       - file: classes/06/worksheet.qmd
       - file: classes/06/slides.qmd
       - file: classes/07/worksheet.qmd
       - file: classes/07/slides.qmd