project:
  type: website
  output-dir: docs

format:
  html:
    theme: cosmo
    toc: true
    math: mathjax

website:
  title: "Math 300 - Discrete Mathematics"
  sidebar:
    contents:
    - text: "Home"
      file: index.qmd
    - text: "Syllabus"
      file: syllabus/syllabus.qmd