---
title: "Week 5 Homework"
number-offset: 4
format:
  html: default
  pdf: default
---

# Week 5 Homework

In order to receive full credit problems and solutions must be clearly written and presented neatly.  In writing up your solution, you should state the problem as explaining the solution.  Merely giving answers to exercises will is not enough to receive credit.  Your write up must show work and convince me that you understand the material.  If you need additional time to complete this assignment, please email me.  Starred ($\bigstar$) proof problems are eligible for inclusion in the proof portfolio assignment.

## Exercises

### Exercise
What is oeis.org? What information can you find about sequences there?
How might you use this resource for this course?


### Exercise
An 8-person committee is to be formed from a group of 15 women and 12
men. In how many ways can the committee be formed if the committee must
contain four men and four women? if there must be at least two men? if
there must be more women than men?


### Exercise
A **palindrome** is a string whose reverse is identical to the original
string. Give examples of bit strings of length 5 and 6 that are
palindromes. How many bit string palindromes of length $n$ are there?
How many ternary string palindromes of length $n$ are there?


### Exercise
How many strings of 6 letters of the english alphabet contain one vowel?
exactly two vowels? at least one vowel? at least two vowels? What is
number of strings of length $n$ with exactly $k$ vowels?


### Exercise
A string that contains only 0s,1s, and 2s is called a **ternary
string**. How many strings of 10 ternary digits (0, 1, or 2) are there
that contain exactly two 0s, three 1s, and five 2s? Generalize this to
the number of ternary strings of length $k$ with $a$ 0's, $b$ 1's, and
$c$ 2's where $a+b+c=k$.


### Exercise
How many integer solutions are there to the equation $x+y+z=8$ for
which: 

1. $x,y ,z$ and are all positive?
2. $x,y ,z$ and are all non-negative?
3. $x,y ,z$ and are all greater than or equal to -3.


### Exercise
How many ways are there to place 15 identical balls into 5 labeled
boxes:

1. Each box has at least one ball?
2. Each box has at least two balls?
3. One box has exactly 10 balls?


### Exercise
Suppose a professor has 10 identical calculators. How many ways are
there to give these calculators to 3 students such that:

1. There are no other conditions?
2. Each student gets 1 calculator?
3. Each student gets 2 calculators?
4. Each student gets 3 calculators?


### Exercise
Your favorite math themed fast food drive-in offers 20 flavors which can
be added to your soda. You have enough money to buy a large soda with 4
added flavors. How many different soda concoctions can you order if:

You refuse to use any of the flavors more than once?  
You refuse repeats but care about the order the flavors are added?  
You allow yourself multiple shots of the same flavor?  
You allow yourself multiple shots, and care about the order the flavors
are added?  

## Proofs

### Proof
Prove $\binom{n}{k}\binom{n-k}{l}=\binom{n}{l}\binom{n-l}{k}$ with
$k+l \leq n$.


### Proof
Let $m$ and $n$ be two integers. Prove that $mn+m$ is odd if and only if
$m$ is odd and $n$ is even. Hint: You will need two subproofs. one for
the if part and one for the only if part.


### Proof
Prove that $n^2+n+1$ is odd for every integer $n$ by direct proof.


### Proof
Let $n$ be a positive integer. Show that
$\binom{2n}{n+1}+\binom{2n}{n}=\frac{1}{2}\binom{2n+2}{n+1}$.


### Proof
Prove
$$\frac{1}{1 \cdot 4}+\frac{1}{4 \cdot 7}+\frac{1}{7 \cdot 10}+ \cdots \frac{1}{(3n-2)(3n+1)}=\frac{n}{3n+1}$$


### Proof
Prove the hexagon property:
$$\binom{n-1}{k-1}\binom{n}{k+1}\binom{n+1}{k}=\binom{n-1}{k}\binom{n+1}{k+1}\binom{n}{k-1}$$


### Proof
$\bigstar$ Prove
$$\sum_{k\ge0}^{}\binom{r}{k}\binom{s}{n-k}=\binom{r+s}{n}$$ Hint: See
Example 1.10 on page 9 of the course text.


### Proof
$\bigstar$ Prove
$$\sum_{k\ge0}^{}k\binom{m}{k}\binom{n}{k}=n\binom{m+n-1}{n}$$ Hint: See
Example 1.10 and 1.11 on page 9 of the course text.


### Proof
$\bigstar$ Use induction to prove that
$1+\frac{1}{\sqrt{2}}+\frac{1}{\sqrt{3}}+\ldots+\frac{1}{\sqrt{n}}\leq 2 \sqrt{n}$
for all positive integers $n$.


### Proof
$\bigstar$ Using induction, prove that
$(\cos{x}+i\sin{x})^n=\cos{nx}+i\sin{nx}$ for $n\ge0$. Hint: Use the
angle addition formulas.


### Proof
$\bigstar$ Prove

$$
\sum_{i=0}^{\lfloor n/2 \rfloor} \binom{n}{2i} = 2^{n-1}
$$

where $\lfloor x \rfloor$ is the floor function.

