---
title: "Week 15 Homework"
format:
  html: default
  pdf: default
---

::: {.callout-note title="Exercise"}
In this problem, boxes can be empty. How many ways are there to
distribute 6 balls in to 3 boxes if\
a. both the balls and boxes are labeled?\
b. balls are labeled, but the boxes are unlabeled?\
c. the balls are unlabeled, but the boxes are labeled?\
d. both the boxes and balls are unlabeled?
:::

::: {.callout-note title="Exercise"}
In this problem, boxes must be non-empty. How many ways are there to
distribute 8 balls in to 4 boxes if\
a. both the balls and boxes are labeled?\
b. balls are labeled, but the boxes are unlabeled?\
c. the balls are unlabeled, but the boxes are labeled?\
d. both the boxes and balls are unlabeled?
:::

::: {.callout-note title="Exercise"}
How many 8-bit strings begin with a 010 or begin with 11? How many 8-bit
strings begin with a 010 or end with 11?
:::

::: {.callout-note title="Exercise"}
Find the number of solutions to $x+y+z=100$ in non-negative integer $x$,
$y$, and $z$, where $x \le 50$, $y \le 40$, and $z \le 30$.
:::

::: {.callout-note title="Exercise"}
How many permutations of the numbers 1 through 8 are there in which none
of the terms 12, 34, 56, 78 appear?
:::

::: {.callout-note title="Exercise"}
How many permutations of the numbers 1 through 8 are there in which none
of the even integers remain in its natural position?
:::

::: {.callout-note title="Exercise"}
Do the enigma machine example from class where the number of rotors is
8, rather than 5.
:::

::: {.callout-note title="Exercise"}
How many permutations of 1,1,2,2,3,3,4,4,5,5 are there in which no two
adjacent numbers are equal?
:::

::: {.callout-note title="Exercise"}
Suppose you roll a 6 sided die 12 times. In how many ways can all 6 six
numbers appear?
:::

::: {.callout-note title="Exercise"}
How many integers in the set of integers from 1 to 1000 are divisible by
a prime number less than 10?
:::

::: {.callout-note title="Exercise"}
A bridge hand consists of 13 cards from a standard 52 card deck. How
many different hands contain at least on card from each of the four
suits?
:::

::: {.callout-note title="Exercise"}
Let $A=\{1,2,3,4,5\}$. How many injective functions $f:A\rightarrow A$
have the property that for each $x$ in $A$, $f(x)\ne x$ ?
:::

::: {.callout-note title="Exercise"}
Suppose you planned on giving 7 gold stars to some of the 13 star
students in your class. Each student can receive at most one star. How
many ways can you do this?
:::

::: {.callout-note title="Exercise"}
What is the formula for the number of ways to place $n$ unlabeled balls
into $k$ unlabeled boxes **without** the restriction that no box may be
empty?
:::

::: {.callout-note title="Exercise"}
What is the formula for the number of ways to place $n$ labeled balls
into $k$ unlabeled boxes **without** the restriction that no box may be
empty?
:::

::: {.callout-note title="Proof"}
Prove by induction $S(n,3)>3^{n-2}$ for all $n\ge 6$.
:::

::: {.callout-note title="Proof"}
$\bigstar$Prove
$$(1-a_1)(1-a_2) \cdots (1-a_k)= 1- (a_1+a_2+ \cdots+a_k)+ (a_1a_2+\cdots +a_{k-1}a_{k})+ \cdots +(-1)^k(a_1 \cdots a_k)$$
:::

::: {.callout-note title="Proof"}
For fixed $m$, find and prove the number of Hamiltonian Paths on on
$K_{m,n}$ as a function of $n$.
:::

::: {.callout-note title="Proof"}
$\bigstar$ From the text, Exercise 4.6
:::

::: {.callout-note title="Proof"}
$\bigstar$ From the text, Exercise 4.7
:::

::: {.callout-note title="Proof"}
$\bigstar$ Let S(n,k) be the Stirling numbers of the second kind. Prove\
a. $S(n, n-1)= \binom{n}{2}$\
b. $S(n, n-2)= \binom{n}{3}+3\binom{n}{4}$
:::

::: {.callout-note title="Proof"}
$\bigstar$ Let S(n,k) be the Stirling numbers of the second kind. Prove
$S(n,k)=\sum_{m=k-1}^{n-1} \binom{n-1}{m} S(m,k-1)$
:::

::: {.callout-note title="Proof"}
$\bigstar$ Show that if $n$ is a positive integer, then
$$n!=\binom{n}{0}d_n+\binom{n}{1}d_{n-1}+\binom{n}{2}d_{n-2}+ \cdots +\binom{n}{n-1}d_1 +\binom{n}{n}d_0$$
where $d_n=(n-1)(d_{n-1}+d_{n-2})$ with $d_1=0$ and $d_2=1$ is the
number of derangements of $n$ objects.
:::

::: {.callout-note title="Proof"}
$\bigstar$ Let $A$ be a subset of $B$ with $|A|=m$ and $|B|=n$, and let
$r$ be an integer $m \le r \le n$. Show the number of $r$ element
subsets of $B$ which contain $A$ as a subset is $\binom{n-m}{r-m}$.
:::

::: {.callout-note title="Proof"}
$\bigstar$ Use the Inclusion-Exclusion Principle to show that for any
non-negative integers $m,r,n$ such that $m \le r \le n$,

$$\binom{n-m}{r-m}=\sum^{m}_{i=0}(-1)^i \binom{m}{i}\binom{n-i}{r}.$$
:::
