---
title: "Week 13 Homework"
number-offset: 12
format:
  html: default
  pdf: default
---


# Week 13 Homework

In order to receive full credit problems and solutions must be clearly written and presented neatly.  In writing up your solution, you should state the problem as explaining the solution.  Merely giving answers to exercises will is not enough to receive credit.  Your write up must show work and convince me that you understand the material.  If you need additional time to complete this assignment, please email me.  Starred ($\bigstar$) proof problems are eligible for inclusion in the proof portfolio assignment.
## Exercises

### Exercise
Find out what the Chinese Postman Problem is. Describe it, and give
examples. What does the Chinese Postman Problem have to do with
Ribonucleic acid (RNA)?


### Exercise
Show that if you delete any vertex and it's incident edges from the
Petersen graph then the resulting graph is Hamiltonian.


### Exercise
From the text, Exercise 4.3.


### Exercise
From the text, Exercise 4.4.


### Exercise
A **Hamiltonian path** is a path that begins and ends at different
vertices but visits each vertex of a graph exactly once. If a graph has
a Hamiltonian cycle, must it have a Hamiltonian path? Explain why or why
not. If a graph has a Hamiltonian path must it have a Hamiltonian cycle?
Explain why or why not.


### Exercise
What are the Worpitzsky numbers? What do they count? What is the
recursive formula for these numbers? Give an example of something they
can be used to count.


### Exercise
From the text, Exercise 5.4.


### Exercise
Find the coefficient of $x$, $x^2$, $x^3$, and $x^4$ in the Taylor
expansion of $$\frac{1}{(1-x)}\frac{1}{(1-x^2)}\frac{1}{(1-x^3)}\cdots$$
and compare to $p(1)$, $p(2)$, $p(3)$, $p(4)$. Do you want to make a
conjecture? (Hint: find the taylor expansion, by multiplying together
each of the fractions Taylor expansion).


### Exercise
Find the definition of Stirling numbers of the first kind. What
recursion relationship do these numbers satisfy? Give examples of the
permutations counted by $s(5,2)$ and $s(6,3)$, where $s(n,k)$ is a
Stirling number of the first kind.


## Proofs

### Proof
Let $s(n,k)$ denote the signless Stirling numbers of the first kind.
Using the recursive formulat $s(n,k)=s(n-1,k-1)+(n-1)s(n-1,k)$, prove
that $$s(n,n-1)=\binom{n}{2}$$.


### Proof
Let $s(n,k)$ denote the signless Stirling numbers of the first kind.
Using the recursive formulat $s(n,k)=s(n-1,k-1)+(n-1)s(n-1,k)$, prove
that
$$s(n,2)=(n-1)!\left( 1 + \frac{1}{2} + \frac{1}{3} + \cdots + \frac{1}{n-1} \right).$$


### Proof
Prove
$$\frac{\binom{2n}{2}\binom{2n-2}{2}\binom{2n-4}{2}\cdots\binom{2}{2}}{n!}=\frac{(2n)!}{2^n \cdot n!}$$


### Proof
$\bigstar$ Prove
$$\frac{\binom{m\cdot n}{n}\binom{(m-1)n}{n}\binom{(m-2)n}{n}\cdots\binom{n}{n}}{m!}=\frac{(m\cdot n)!}{(n!)^m \cdot m!}$$


### Proof
$\bigstar$ Let $s(n,k)$ denote the signless Stirling numbers of the
first kind. Use the recursive formula $s(n,k)=s(n-1,k-1)+(n-1)s(n-1,k)$
to find a formula for $s(n,n-2)$ and prove it.


### Proof
$\bigstar$ Suppose $G$ is a graph with $n$ vertices, each of which has
degree $d \ge (n-1)/2$. Prove that $G$ contains a Hamiltonian path.
Hint: Add an extra vertex to $G$ and connect it to all the other
vertices. What does Dirac's Theorem say about this new graph.)


### Proof
$\bigstar$ Prove $\sum^n_{r=0}\binom{n}{r}2^{2n-2r}=5^n$

