---
title: "Week 10 Homework"
number-offset: 9
format:
  html: default
  pdf: default
---

# Week 10 Homework

In order to receive full credit problems and solutions must be clearly written and presented neatly.  In writing up your solution, you should state the problem as explaining the solution.  Merely giving answers to exercises will is not enough to receive credit.  Your write up must show work and convince me that you understand the material.  If you need additional time to complete this assignment, please email me.  Starred ($\bigstar$) proof problems are eligible for inclusion in the proof portfolio assignment.

## Exercises

### Exercise
From the text, Exercise 3.2.


### Exercise
From the text, Exercise 3.11.


### Exercise
Find the definition for **isomorphic** graphs. What is the definition?
Give an example of two graphs that are isomorphic, and give an example
of two graphs that are not isomorphic.


### Exercise
A simple graph $G$ is **self-complimentary** if $G$ and $\bar{G}$ are
isomorphic. Find a self-complimentary graph having five vertices. Find
another self complimentary graph with more than 1 vertex.


### Exercise
A vertex $v$ in a connected graph $G$ is an **articulation point** if
the removal of $v$ and all edges incident to $v$ disconnects $G$. Give
an example of a graph with six vertices that has exactly two
articulation points. Give an example of a graph on six vertices that has
no articulation points.


### Proof
Prove that if G is a simple graph with $p$ vertices, where each vertex
has degree $\ge \frac{1}{2}(p-1)$, then $G$ must be connected. Hint: Try
a contradiction proof, by assuming there are at least two components of
$G$. How many vertices must each component have?

## Proofs

### Proof
Prove the statement: In any tree there is exactly one path from any
vertex to any other vertex. (Hint: Try contradiction. If there are two
paths try to show there is a cycle.)


### Proof
A **forest** is a simple graph where each component is a tree. Find a
formula for the number of edges in a forest with $n$ vertices and $c$
components. Prove your formula.


### Proof
Prove the average degree in a tree is always less than 2. More
specifically express this average as a function of the number of
vertices in tree.


### Proof
$\bigstar$ Let $v$ and $w$ be distinct vertices in the complete graph
$K_n$ for $n \ge 2$. Prove the number of paths from $v$ to $w$ is
$$(n-2)!\sum^{n-2}_{k=0}\frac{1}{k!}$$


### Proof
$\bigstar$ Prove that a vertex $v$ in a connected graph $G$ is an
articulation point if and only if there are vertices $w$ and $x$ in $G$
having the property that every path from $w$ to $x$ passes through $v$.


### Proof
$\bigstar$ Prove that in any simple graph with more than one vertex,
there must be two vertices with the same degree. (Hint: Try
contradiction.)


### Proof
$\bigstar$ Prove the number of vertices of degree 1 in an tree must be
greater than or equal to the maximum degree in the tree.

