---
title: "Week 3 Homework"
number-offset: 2
format:
  html: default
  pdf: default
---

# Week 3 Homework

In order to receive full credit problems and solutions must be clearly written and presented neatly.  In writing up your solution, you should state the problem as explaining the solution.  Merely giving answers to exercises will is not enough to receive credit.  Your write up must show work and convince me that you understand the material.  If you need additional time to complete this assignment, please email me.  Starred ($\bigstar$) proof problems are eligible for inclusion in the proof portfolio assignment.

## Exercises

### Exercise
Do research on the difference between weak induction and strong
induction. Explain the difference between the two and give an example
proof of strong induction and an example proof of weak induction.


### Exercise
Find and explain the flaw or flaws in the following proof:\
"Claim:" For every positive integer $n$,
$\sum^{n}_{i=1}i=\frac{(n+\frac{1}{2})^2}{2}$ .\
Base Case: The formula is true for n=1.\
Inductive Step: Suppose $\sum^{n}_{i=1}i=\frac{(n+\frac{1}{2})^2}{2}$.
Then $\sum^{n+1}_{i=1}i=(\sum^{n}_{i=1}i) + (n+1)$. By induction
hypothesis, $$
\sum^{n+1}_{i=1}i = \frac{(n+\frac{1}{2})^2}{2} +n+1\\
= \frac{(n^2+n+\frac{1}{4})}{2}+n+1 \\
=  \frac{(n^2+3n+\frac{9}{4})}{2} \\
= \frac{(n+\frac{3}{2})^2}{2} \\
= \frac{((n+1)+\frac{1}{2})^2}{2}
$$ completing the induction proof.


### Exercise
How many strings of 2 lowercase letters have the letter *x* in them? How
many strings of 4 lowercase letters have the letter *x* in them? How
many strings of $k$ lowercase letters have the letter *x* in them?


### Exercise
A small auditorium labels its seats with one of the 26 a-z letters and
one of the ten digits 0-9. How many different seat labels are possible?
What is the answer if each seat is labeled with one of the letters a-z
and one of the number 1-100? What is the answer if each seat is labeled
with two letters and two digits?


### Exercise
How many different decimal strings of length 2 (strings of length two
where each element of the string is one of the decimal digits 0-9) are
there where no digit can be repeated? How many length 3 decimal strings
are there like this. How many length 7 decimal strings are there like
this? How many length 11 decimal strings are there like this? Give an
example, or explain why it is not possible, of one of the length 11
strings.


### Exercise
Consider placing $n$ people around a circular table where it does not
matter which seat each person is in, but it does matter who is on the
right and left. That if, if one arrangement of people can be rotated to
be the same as another arrangement, then the arrangements are the same.
How many different ways can the $n$ people be placed around the table?


### Exercise
A **bit string** of length $k$ is a string of $k$ binary digits (0 or
1). How many bit strings are there of length 6 or less? How many bit
strings of length 6 begin and end with a 1? How many bit strings of
length $k$ begin and end with a 1? How many bit strings of length $n$
have at least $k$ 1's where $k \le n$?


### Exercise
At a CI, students are given a 9 digit student ID number. How many
different ID numbers are there? How many read the same forward and
backward? How many contain only odd digits? How many have at least on
even digit?


### Exercise
We usually write numbers in decimal form (or base 10), meaning numbers
are composed using 10 different "digits" . Sometimes though it is useful
to write numbers hexadecimal or base 16. Now there are 16 distinct
digits that can be used to form numbers:
$\{0,1,2,3,4,5,6,7,8,9,A,B,C,DE,F\}$. So for example, a 3 digit
hexadecimal number might be 2B8.

How many 2-digit hexadecimals are there in which the first digit is E or
F? Explain your answer in terms of the additive principle (using either
events or sets).

Explain why your answer to the previous part is correct in terms of the
multiplicative principle (using either events or sets). Why do both the
additive and multiplicative principles give you the same answer?

How many 3-digit hexadecimals start with a letter (A-F) and end with a
numeral (0-9)? Explain.

How many 3-digit hexadecimals start with a letter (A-F) or end with a
numeral (0-9) (or both)? Explain.


## Proofs

### Proof
Use induction to prove:
$${1\cdot2}+{2\cdot3}+{3\cdot4}+\cdots+{n(n+1)}=\frac{n(n+1)(n+2)}{3}$$


### Proof
Use induction to prove: $$\frac{d}{dx}x^n=n\cdot x^{n-1}$$


### Proof
Use induction to prove:
$$1^2+3^2+5^2 + \ldots +(2n-1)^2=\frac{4n^3-n}{3}$$


### Proof
Use induction to prove:
$$1\cdot3+2\cdot4+3\cdot5 + \ldots +n(n+2)=\frac{n(n+1)(2n+7)}{6}$$


### Proof
Use induction to prove: $$1+5+9 + \ldots +4n-3=n(2n-1)$$


### Proof
Prove by induction:
$$
\begin{pmatrix}
5 & -1 \\
4 & 1
\end{pmatrix}^n
=
3^{n-1}
\begin{pmatrix}
2n+3 & -n \\
4n & 3-2n
\end{pmatrix}
$$


### Proof
$\bigstar$ Use induction to prove that the $n^{th}$ derivative of
$\ln x$ is $$f^{(n)}(x)=\frac{(-1)^{n+1}(n-1)!}{x^n}$$


### Proof
$\bigstar$ Use induction to prove that the $n^{th}$ derivative of
$x e^{-x}$ is $$f^{(n)}(x)=(-1)^{n}e^{-x}(x-n)$$ for $n$ a positive
integer.


### Proof
$\bigstar$ Use induction to prove for $n \ge 1$:
$$1+\frac{1}{\sqrt{2}}+\frac{1}{\sqrt{3}}+ \cdots +\frac{1}{\sqrt{n}}> 2(\sqrt{n+1}-1)$$

